[{"title":"BugVersion","href":"neSparkle.BugVersion.htm"}
,{"title":"MajorVersion","href":"neSparkle.MajorVersion.htm"}
,{"title":"MinorVersion","href":"neSparkle.MinorVersion.htm"}
,{"title":"neSparkle","href":"neSparkle.htm"}
,{"title":"neSparkle.TCallbackArray","href":"neSparkle.TCallbackArray.htm"}
,{"title":"neSparkle.TCallbackArrayFunctions","href":"neSparkle.TCallbackArrayFunctions.htm"}
,{"title":"neSparkle.TCallbackType","href":"neSparkle.TCallbackType.htm"}
,{"title":"neSparkle.TCallbackTypeFunc","href":"neSparkle.TCallbackTypeFunc.htm"}
,{"title":"neSparkle.TneSparkle","href":"neSparkle.TneSparkle.htm"}
,{"title":"neSparkle.TUpdateType","href":"neSparkle.TUpdateType.htm"}
,{"title":"neSparklePackage","href":"neSparklePackage.htm"}
,{"title":"TCallbackArray","href":"neSparkle.TCallbackArray.htm"}
,{"title":"TCallbackArrayFunctions","href":"neSparkle.TCallbackArrayFunctions.htm"}
,{"title":"TCallbackType","href":"neSparkle.TCallbackType.htm"}
,{"title":"TCallbackType.cbDidFindUpdate","href":"neSparkle.TCallbackType.htm"}
,{"title":"TCallbackType.cbDidNotFindUpdate","href":"neSparkle.TCallbackType.htm"}
,{"title":"TCallbackType.cbError","href":"neSparkle.TCallbackType.htm"}
,{"title":"TCallbackType.cbShutdown","href":"neSparkle.TCallbackType.htm"}
,{"title":"TCallbackType.cbUpdateCancelled","href":"neSparkle.TCallbackType.htm"}
,{"title":"TCallbackTypeFunc","href":"neSparkle.TCallbackTypeFunc.htm"}
,{"title":"TCallbackTypeFunc.cbCanShutdown","href":"neSparkle.TCallbackTypeFunc.htm"}
,{"title":"TneSparkle","href":"neSparkle.TneSparkle.htm"}
,{"title":"TneSparkle.AppBuildVersion","href":"neSparkle.TneSparkle.AppBuildVersion.htm"}
,{"title":"TneSparkle.AppcastURL","href":"neSparkle.TneSparkle.AppcastURL.htm"}
,{"title":"TneSparkle.AutoCheckForUpdates","href":"neSparkle.TneSparkle.AutoCheckForUpdates.htm"}
,{"title":"TneSparkle.CheckUpdate(TUpdateType)","href":"neSparkle.TneSparkle.CheckUpdate.htm"}
,{"title":"TneSparkle.CheckUpdateWithoutUI","href":"neSparkle.TneSparkle.CheckUpdateWithoutUI.htm"}
,{"title":"TneSparkle.CheckUpdateWithUI","href":"neSparkle.TneSparkle.CheckUpdateWithUI.htm"}
,{"title":"TneSparkle.CheckUpdateWithUIandInstall","href":"neSparkle.TneSparkle.CheckUpdateWithUIandInstall.htm"}
,{"title":"TneSparkle.Cleanup","href":"neSparkle.TneSparkle.Cleanup.htm"}
,{"title":"TneSparkle.Create","href":"neSparkle.TneSparkle.Create.htm"}
,{"title":"TneSparkle.Create(string)","href":"neSparkle.TneSparkle.Create(string).htm"}
,{"title":"TneSparkle.Destroy","href":"neSparkle.TneSparkle.Destroy.htm"}
,{"title":"TneSparkle.DLLLoaded","href":"neSparkle.TneSparkle.DLLLoaded.htm"}
,{"title":"TneSparkle.DLLPath","href":"neSparkle.TneSparkle.DLLPath.htm"}
,{"title":"TneSparkle.DSAPublicPem","href":"neSparkle.TneSparkle.DSAPublicPem.htm"}
,{"title":"TneSparkle.ExecuteReferencedFunctionBoolean(PWideChar,TCallbackTypeFunc,TFunc)","href":"neSparkle.TneSparkle.ExecuteReferencedFunctionBoolean.htm"}
,{"title":"TneSparkle.ExecuteReferencedProcedure(PWideChar,TCallbackType,TProc)","href":"neSparkle.TneSparkle.ExecuteReferencedProcedure.htm"}
,{"title":"TneSparkle.ExecuteSimpleProcedure(PWideChar)","href":"neSparkle.TneSparkle.ExecuteSimpleProcedure.htm"}
,{"title":"TneSparkle.fAppBuildVersion","href":"neSparkle.TneSparkle.fAppBuildVersion.htm"}
,{"title":"TneSparkle.fAppcastURL","href":"neSparkle.TneSparkle.fAppcastURL.htm"}
,{"title":"TneSparkle.fAppName","href":"neSparkle.TneSparkle.fAppName.htm"}
,{"title":"TneSparkle.fAppVersion","href":"neSparkle.TneSparkle.fAppVersion.htm"}
,{"title":"TneSparkle.fCompanyName","href":"neSparkle.TneSparkle.fCompanyName.htm"}
,{"title":"TneSparkle.fDLLPath","href":"neSparkle.TneSparkle.fDLLPath.htm"}
,{"title":"TneSparkle.fDSAPublicPem","href":"neSparkle.TneSparkle.fDSAPublicPem.htm"}
,{"title":"TneSparkle.fHandle","href":"neSparkle.TneSparkle.fHandle.htm"}
,{"title":"TneSparkle.fOnCanShutDown","href":"neSparkle.TneSparkle.fOnCanShutDown.htm"}
,{"title":"TneSparkle.fOnDidFindUpdate","href":"neSparkle.TneSparkle.fOnDidFindUpdate.htm"}
,{"title":"TneSparkle.fOnDidNotFindUpdate","href":"neSparkle.TneSparkle.fOnDidNotFindUpdate.htm"}
,{"title":"TneSparkle.fOnError","href":"neSparkle.TneSparkle.fOnError.htm"}
,{"title":"TneSparkle.fOnShutDown","href":"neSparkle.TneSparkle.fOnShutDown.htm"}
,{"title":"TneSparkle.fOnUpdateCancelled","href":"neSparkle.TneSparkle.fOnUpdateCancelled.htm"}
,{"title":"TneSparkle.fRegistryPath","href":"neSparkle.TneSparkle.fRegistryPath.htm"}
,{"title":"TneSparkle.GetAppBuildVersion","href":"neSparkle.TneSparkle.GetAppBuildVersion.htm"}
,{"title":"TneSparkle.GetAppcastURL","href":"neSparkle.TneSparkle.GetAppcastURL.htm"}
,{"title":"TneSparkle.GetAutoCheckForUpdates","href":"neSparkle.TneSparkle.GetAutoCheckForUpdates.htm"}
,{"title":"TneSparkle.getDLLLoaded","href":"neSparkle.TneSparkle.getDLLLoaded.htm"}
,{"title":"TneSparkle.GetLastCheckTime","href":"neSparkle.TneSparkle.GetLastCheckTime.htm"}
,{"title":"TneSparkle.GetRegistryPath","href":"neSparkle.TneSparkle.GetRegistryPath.htm"}
,{"title":"TneSparkle.GetUpdateCheckInterval","href":"neSparkle.TneSparkle.GetUpdateCheckInterval.htm"}
,{"title":"TneSparkle.Init","href":"neSparkle.TneSparkle.Init.htm"}
,{"title":"TneSparkle.LastCheckTime","href":"neSparkle.TneSparkle.LastCheckTime.htm"}
,{"title":"TneSparkle.OnCanShutDown","href":"neSparkle.TneSparkle.OnCanShutDown.htm"}
,{"title":"TneSparkle.OnDidFindUpdate","href":"neSparkle.TneSparkle.OnDidFindUpdate.htm"}
,{"title":"TneSparkle.OnDidNotFindUpdate","href":"neSparkle.TneSparkle.OnDidNotFindUpdate.htm"}
,{"title":"TneSparkle.OnError","href":"neSparkle.TneSparkle.OnError.htm"}
,{"title":"TneSparkle.OnShutDown","href":"neSparkle.TneSparkle.OnShutDown.htm"}
,{"title":"TneSparkle.OnUpdateCancelled","href":"neSparkle.TneSparkle.OnUpdateCancelled.htm"}
,{"title":"TneSparkle.RegistryPath","href":"neSparkle.TneSparkle.RegistryPath.htm"}
,{"title":"TneSparkle.ResetUpdateCheckInterval","href":"neSparkle.TneSparkle.ResetUpdateCheckInterval.htm"}
,{"title":"TneSparkle.SetAppBuildVersion(string)","href":"neSparkle.TneSparkle.SetAppBuildVersion.htm"}
,{"title":"TneSparkle.SetAppcastURL(string)","href":"neSparkle.TneSparkle.SetAppcastURL.htm"}
,{"title":"TneSparkle.SetAppDetails(string,string,string)","href":"neSparkle.TneSparkle.SetAppDetails.htm"}
,{"title":"TneSparkle.SetAutoCheckForUpdates(Boolean)","href":"neSparkle.TneSparkle.SetAutoCheckForUpdates.htm"}
,{"title":"TneSparkle.setDSAPublicPem(String)","href":"neSparkle.TneSparkle.setDSAPublicPem.htm"}
,{"title":"TneSparkle.SetLang(string)","href":"neSparkle.TneSparkle.SetLang.htm"}
,{"title":"TneSparkle.SetLangID(ShortInt)","href":"neSparkle.TneSparkle.SetLangID.htm"}
,{"title":"TneSparkle.SetOnCanShutDown(TFunc)","href":"neSparkle.TneSparkle.SetOnCanShutDown.htm"}
,{"title":"TneSparkle.SetOnDidFindUpdate(TProc)","href":"neSparkle.TneSparkle.SetOnDidFindUpdate.htm"}
,{"title":"TneSparkle.SetOnDidNotFindUpdate(TProc)","href":"neSparkle.TneSparkle.SetOnDidNotFindUpdate.htm"}
,{"title":"TneSparkle.SetOnError(TProc)","href":"neSparkle.TneSparkle.SetOnError.htm"}
,{"title":"TneSparkle.SetOnShutDown(TProc)","href":"neSparkle.TneSparkle.SetOnShutDown.htm"}
,{"title":"TneSparkle.SetOnUpdateCancelled(TProc)","href":"neSparkle.TneSparkle.SetOnUpdateCancelled.htm"}
,{"title":"TneSparkle.SetRegistryPath(string)","href":"neSparkle.TneSparkle.SetRegistryPath.htm"}
,{"title":"TneSparkle.SetUpdateCheckInterval(Integer)","href":"neSparkle.TneSparkle.SetUpdateCheckInterval.htm"}
,{"title":"TneSparkle.UpdateCheckInterval","href":"neSparkle.TneSparkle.UpdateCheckInterval.htm"}
,{"title":"TUpdateType","href":"neSparkle.TUpdateType.htm"}
,{"title":"TUpdateType.utWithoutUI","href":"neSparkle.TUpdateType.htm"}
,{"title":"TUpdateType.utWithUI","href":"neSparkle.TUpdateType.htm"}
,{"title":"TUpdateType.utWithUIAndInstall","href":"neSparkle.TUpdateType.htm"}
,{"title":"WinSparkleLib","href":"neSparkle.WinSparkleLib.htm"}
,{"title":"WinSparkleVersion","href":"neSparkle.WinSparkleVersion.htm"}
]