[{"title":"BugVersion","href":"WinSparkle.BugVersion.htm"}
,{"title":"callbackFuncs","href":"WinSparkle.callbackFuncs.htm"}
,{"title":"callbackProcs","href":"WinSparkle.callbackProcs.htm"}
,{"title":"DelphiSparkleExample","href":"DelphiSparkleExample.htm"}
,{"title":"DoOnCanShutdown","href":"WinSparkle.DoOnCanShutdown.htm"}
,{"title":"DoOnError","href":"WinSparkle.DoOnError.htm"}
,{"title":"DoOnShutDown","href":"WinSparkle.DoOnShutDown.htm"}
,{"title":"DoOnUpdateCancelled","href":"WinSparkle.DoOnUpdateCancelled.htm"}
,{"title":"DoOnUpdateFound","href":"WinSparkle.DoOnUpdateFound.htm"}
,{"title":"DoOnUpdateNotFound","href":"WinSparkle.DoOnUpdateNotFound.htm"}
,{"title":"MajorVersion","href":"WinSparkle.MajorVersion.htm"}
,{"title":"MinorVersion","href":"WinSparkle.MinorVersion.htm"}
,{"title":"TCallbackArray","href":"WinSparkle.TCallbackArray.htm"}
,{"title":"TCallbackArrayFunctions","href":"WinSparkle.TCallbackArrayFunctions.htm"}
,{"title":"TCallbackType","href":"WinSparkle.TCallbackType.htm"}
,{"title":"TCallbackType.cbDidFindUpdate","href":"WinSparkle.TCallbackType.htm"}
,{"title":"TCallbackType.cbDidNotFindUpdate","href":"WinSparkle.TCallbackType.htm"}
,{"title":"TCallbackType.cbError","href":"WinSparkle.TCallbackType.htm"}
,{"title":"TCallbackType.cbShutdown","href":"WinSparkle.TCallbackType.htm"}
,{"title":"TCallbackType.cbUpdateCancelled","href":"WinSparkle.TCallbackType.htm"}
,{"title":"TCallbackTypeFunc","href":"WinSparkle.TCallbackTypeFunc.htm"}
,{"title":"TCallbackTypeFunc.cbCanShutdown","href":"WinSparkle.TCallbackTypeFunc.htm"}
,{"title":"TUpdateType","href":"WinSparkle.TUpdateType.htm"}
,{"title":"TUpdateType.utWithoutUI","href":"WinSparkle.TUpdateType.htm"}
,{"title":"TUpdateType.utWithUI","href":"WinSparkle.TUpdateType.htm"}
,{"title":"TUpdateType.utWithUIAndInstall","href":"WinSparkle.TUpdateType.htm"}
,{"title":"TWinSparkle","href":"WinSparkle.TWinSparkle.htm"}
,{"title":"TWinSparkle.AppBuildVersion","href":"WinSparkle.TWinSparkle.AppBuildVersion.htm"}
,{"title":"TWinSparkle.AppcastURL","href":"WinSparkle.TWinSparkle.AppcastURL.htm"}
,{"title":"TWinSparkle.AutoCheckForUpdates","href":"WinSparkle.TWinSparkle.AutoCheckForUpdates.htm"}
,{"title":"TWinSparkle.CheckUpdate(TUpdateType)","href":"WinSparkle.TWinSparkle.CheckUpdate.htm"}
,{"title":"TWinSparkle.CheckUpdateWithoutUI","href":"WinSparkle.TWinSparkle.CheckUpdateWithoutUI.htm"}
,{"title":"TWinSparkle.CheckUpdateWithUI","href":"WinSparkle.TWinSparkle.CheckUpdateWithUI.htm"}
,{"title":"TWinSparkle.CheckUpdateWithUIandInstall","href":"WinSparkle.TWinSparkle.CheckUpdateWithUIandInstall.htm"}
,{"title":"TWinSparkle.Cleanup","href":"WinSparkle.TWinSparkle.Cleanup.htm"}
,{"title":"TWinSparkle.Create","href":"WinSparkle.TWinSparkle.Create.htm"}
,{"title":"TWinSparkle.Create(string)","href":"WinSparkle.TWinSparkle.Create(string).htm"}
,{"title":"TWinSparkle.Destroy","href":"WinSparkle.TWinSparkle.Destroy.htm"}
,{"title":"TWinSparkle.DLLLoaded","href":"WinSparkle.TWinSparkle.DLLLoaded.htm"}
,{"title":"TWinSparkle.DLLPath","href":"WinSparkle.TWinSparkle.DLLPath.htm"}
,{"title":"TWinSparkle.Init","href":"WinSparkle.TWinSparkle.Init.htm"}
,{"title":"TWinSparkle.LastCheckTime","href":"WinSparkle.TWinSparkle.LastCheckTime.htm"}
,{"title":"TWinSparkle.OnCanShutDown","href":"WinSparkle.TWinSparkle.OnCanShutDown.htm"}
,{"title":"TWinSparkle.OnDidFindUpdate","href":"WinSparkle.TWinSparkle.OnDidFindUpdate.htm"}
,{"title":"TWinSparkle.OnDidNotFindUpdate","href":"WinSparkle.TWinSparkle.OnDidNotFindUpdate.htm"}
,{"title":"TWinSparkle.OnError","href":"WinSparkle.TWinSparkle.OnError.htm"}
,{"title":"TWinSparkle.OnShutDown","href":"WinSparkle.TWinSparkle.OnShutDown.htm"}
,{"title":"TWinSparkle.OnUpdateCancelled","href":"WinSparkle.TWinSparkle.OnUpdateCancelled.htm"}
,{"title":"TWinSparkle.RegistryPath","href":"WinSparkle.TWinSparkle.RegistryPath.htm"}
,{"title":"TWinSparkle.ResetUpdateCheckInterval","href":"WinSparkle.TWinSparkle.ResetUpdateCheckInterval.htm"}
,{"title":"TWinSparkle.SetAppDetails(string,string,string)","href":"WinSparkle.TWinSparkle.SetAppDetails.htm"}
,{"title":"TWinSparkle.SetLang(string)","href":"WinSparkle.TWinSparkle.SetLang.htm"}
,{"title":"TWinSparkle.SetLangID(ShortInt)","href":"WinSparkle.TWinSparkle.SetLangID.htm"}
,{"title":"TWinSparkle.UpdateCheckInterval","href":"WinSparkle.TWinSparkle.UpdateCheckInterval.htm"}
,{"title":"WinSparkle","href":"WinSparkle.htm"}
,{"title":"WinSparkle.TCallbackArray","href":"WinSparkle.TCallbackArray.htm"}
,{"title":"WinSparkle.TCallbackArrayFunctions","href":"WinSparkle.TCallbackArrayFunctions.htm"}
,{"title":"WinSparkle.TCallbackType","href":"WinSparkle.TCallbackType.htm"}
,{"title":"WinSparkle.TCallbackTypeFunc","href":"WinSparkle.TCallbackTypeFunc.htm"}
,{"title":"WinSparkle.TUpdateType","href":"WinSparkle.TUpdateType.htm"}
,{"title":"WinSparkle.TWinSparkle","href":"WinSparkle.TWinSparkle.htm"}
,{"title":"WinSparkleLib","href":"WinSparkle.WinSparkleLib.htm"}
]