[{"title":"BugVersion","href":"neSparkle.BugVersion.htm"}
,{"title":"callbackFuncs","href":"neSparkle.callbackFuncs.htm"}
,{"title":"callbackProcs","href":"neSparkle.callbackProcs.htm"}
,{"title":"DoOnCanShutdown","href":"neSparkle.DoOnCanShutdown.htm"}
,{"title":"DoOnError","href":"neSparkle.DoOnError.htm"}
,{"title":"DoOnShutDown","href":"neSparkle.DoOnShutDown.htm"}
,{"title":"DoOnUpdateCancelled","href":"neSparkle.DoOnUpdateCancelled.htm"}
,{"title":"DoOnUpdateFound","href":"neSparkle.DoOnUpdateFound.htm"}
,{"title":"DoOnUpdateNotFound","href":"neSparkle.DoOnUpdateNotFound.htm"}
,{"title":"MajorVersion","href":"neSparkle.MajorVersion.htm"}
,{"title":"MinorVersion","href":"neSparkle.MinorVersion.htm"}
,{"title":"neSparkle","href":"neSparkle.htm"}
,{"title":"neSparkle.TCallbackArray","href":"neSparkle.TCallbackArray.htm"}
,{"title":"neSparkle.TCallbackArrayFunctions","href":"neSparkle.TCallbackArrayFunctions.htm"}
,{"title":"neSparkle.TCallbackType","href":"neSparkle.TCallbackType.htm"}
,{"title":"neSparkle.TCallbackTypeFunc","href":"neSparkle.TCallbackTypeFunc.htm"}
,{"title":"neSparkle.TneSparkle","href":"neSparkle.TneSparkle.htm"}
,{"title":"neSparkle.TUpdateType","href":"neSparkle.TUpdateType.htm"}
,{"title":"neSparklePackage","href":"neSparklePackage.htm"}
,{"title":"TCallbackArray","href":"neSparkle.TCallbackArray.htm"}
,{"title":"TCallbackArrayFunctions","href":"neSparkle.TCallbackArrayFunctions.htm"}
,{"title":"TCallbackType","href":"neSparkle.TCallbackType.htm"}
,{"title":"TCallbackType.cbDidFindUpdate","href":"neSparkle.TCallbackType.htm"}
,{"title":"TCallbackType.cbDidNotFindUpdate","href":"neSparkle.TCallbackType.htm"}
,{"title":"TCallbackType.cbError","href":"neSparkle.TCallbackType.htm"}
,{"title":"TCallbackType.cbShutdown","href":"neSparkle.TCallbackType.htm"}
,{"title":"TCallbackType.cbUpdateCancelled","href":"neSparkle.TCallbackType.htm"}
,{"title":"TCallbackTypeFunc","href":"neSparkle.TCallbackTypeFunc.htm"}
,{"title":"TCallbackTypeFunc.cbCanShutdown","href":"neSparkle.TCallbackTypeFunc.htm"}
,{"title":"TneSparkle","href":"neSparkle.TneSparkle.htm"}
,{"title":"TneSparkle.AppBuildVersion","href":"neSparkle.TneSparkle.AppBuildVersion.htm"}
,{"title":"TneSparkle.AppcastURL","href":"neSparkle.TneSparkle.AppcastURL.htm"}
,{"title":"TneSparkle.AutoCheckForUpdates","href":"neSparkle.TneSparkle.AutoCheckForUpdates.htm"}
,{"title":"TneSparkle.CheckUpdate(TUpdateType)","href":"neSparkle.TneSparkle.CheckUpdate.htm"}
,{"title":"TneSparkle.CheckUpdateWithoutUI","href":"neSparkle.TneSparkle.CheckUpdateWithoutUI.htm"}
,{"title":"TneSparkle.CheckUpdateWithUI","href":"neSparkle.TneSparkle.CheckUpdateWithUI.htm"}
,{"title":"TneSparkle.CheckUpdateWithUIandInstall","href":"neSparkle.TneSparkle.CheckUpdateWithUIandInstall.htm"}
,{"title":"TneSparkle.Cleanup","href":"neSparkle.TneSparkle.Cleanup.htm"}
,{"title":"TneSparkle.Create","href":"neSparkle.TneSparkle.Create.htm"}
,{"title":"TneSparkle.Create(string)","href":"neSparkle.TneSparkle.Create(string).htm"}
,{"title":"TneSparkle.Destroy","href":"neSparkle.TneSparkle.Destroy.htm"}
,{"title":"TneSparkle.DLLLoaded","href":"neSparkle.TneSparkle.DLLLoaded.htm"}
,{"title":"TneSparkle.DLLPath","href":"neSparkle.TneSparkle.DLLPath.htm"}
,{"title":"TneSparkle.Init","href":"neSparkle.TneSparkle.Init.htm"}
,{"title":"TneSparkle.LastCheckTime","href":"neSparkle.TneSparkle.LastCheckTime.htm"}
,{"title":"TneSparkle.OnCanShutDown","href":"neSparkle.TneSparkle.OnCanShutDown.htm"}
,{"title":"TneSparkle.OnDidFindUpdate","href":"neSparkle.TneSparkle.OnDidFindUpdate.htm"}
,{"title":"TneSparkle.OnDidNotFindUpdate","href":"neSparkle.TneSparkle.OnDidNotFindUpdate.htm"}
,{"title":"TneSparkle.OnError","href":"neSparkle.TneSparkle.OnError.htm"}
,{"title":"TneSparkle.OnShutDown","href":"neSparkle.TneSparkle.OnShutDown.htm"}
,{"title":"TneSparkle.OnUpdateCancelled","href":"neSparkle.TneSparkle.OnUpdateCancelled.htm"}
,{"title":"TneSparkle.RegistryPath","href":"neSparkle.TneSparkle.RegistryPath.htm"}
,{"title":"TneSparkle.ResetUpdateCheckInterval","href":"neSparkle.TneSparkle.ResetUpdateCheckInterval.htm"}
,{"title":"TneSparkle.SetAppDetails(string,string,string)","href":"neSparkle.TneSparkle.SetAppDetails.htm"}
,{"title":"TneSparkle.SetLang(string)","href":"neSparkle.TneSparkle.SetLang.htm"}
,{"title":"TneSparkle.SetLangID(ShortInt)","href":"neSparkle.TneSparkle.SetLangID.htm"}
,{"title":"TneSparkle.UpdateCheckInterval","href":"neSparkle.TneSparkle.UpdateCheckInterval.htm"}
,{"title":"TUpdateType","href":"neSparkle.TUpdateType.htm"}
,{"title":"TUpdateType.utWithoutUI","href":"neSparkle.TUpdateType.htm"}
,{"title":"TUpdateType.utWithUI","href":"neSparkle.TUpdateType.htm"}
,{"title":"TUpdateType.utWithUIAndInstall","href":"neSparkle.TUpdateType.htm"}
,{"title":"WinSparkleLib","href":"neSparkle.WinSparkleLib.htm"}
,{"title":"WinSprkaleVersion","href":"neSparkle.WinSprkaleVersion.htm"}
]