[{"title":"DelphiSparkleExample","key":"DelphiSparkleExample","href":"DelphiSparkleExample.htm","activate":true,"children":[{"title":"WinSparkle","key":"WinSparkle","href":"WinSparkle.htm","children":[{"title":"Classes","key":"WinSparkle_Classes","href":"WinSparkle_Classes.htm","children":[{"title":"TWinSparkle","key":"WinSparkle.TWinSparkle","href":"WinSparkle.TWinSparkle.htm","children":[{"title":"Constructors","key":"WinSparkle.TWinSparkle_Constructors","href":"WinSparkle.TWinSparkle_Constructors.htm","children":[{"title":"Create","key":"WinSparkle.TWinSparkle.Create","href":"WinSparkle.TWinSparkle.Create.htm"}
,{"title":"Create(string)","key":"WinSparkle.TWinSparkle.Create(string)","href":"WinSparkle.TWinSparkle.Create(string).htm"}
,{"title":"Destroy","key":"WinSparkle.TWinSparkle.Destroy","href":"WinSparkle.TWinSparkle.Destroy.htm"}
]}
,{"title":"Properties","key":"WinSparkle.TWinSparkle_Properties","href":"WinSparkle.TWinSparkle_Properties.htm","children":[{"title":"AppBuildVersion","key":"WinSparkle.TWinSparkle.AppBuildVersion","href":"WinSparkle.TWinSparkle.AppBuildVersion.htm"}
,{"title":"AppcastURL","key":"WinSparkle.TWinSparkle.AppcastURL","href":"WinSparkle.TWinSparkle.AppcastURL.htm"}
,{"title":"AutoCheckForUpdates","key":"WinSparkle.TWinSparkle.AutoCheckForUpdates","href":"WinSparkle.TWinSparkle.AutoCheckForUpdates.htm"}
,{"title":"DLLLoaded","key":"WinSparkle.TWinSparkle.DLLLoaded","href":"WinSparkle.TWinSparkle.DLLLoaded.htm"}
,{"title":"DLLPath","key":"WinSparkle.TWinSparkle.DLLPath","href":"WinSparkle.TWinSparkle.DLLPath.htm"}
,{"title":"LastCheckTime","key":"WinSparkle.TWinSparkle.LastCheckTime","href":"WinSparkle.TWinSparkle.LastCheckTime.htm"}
,{"title":"OnCanShutDown","key":"WinSparkle.TWinSparkle.OnCanShutDown","href":"WinSparkle.TWinSparkle.OnCanShutDown.htm"}
,{"title":"OnDidFindUpdate","key":"WinSparkle.TWinSparkle.OnDidFindUpdate","href":"WinSparkle.TWinSparkle.OnDidFindUpdate.htm"}
,{"title":"OnDidNotFindUpdate","key":"WinSparkle.TWinSparkle.OnDidNotFindUpdate","href":"WinSparkle.TWinSparkle.OnDidNotFindUpdate.htm"}
,{"title":"OnError","key":"WinSparkle.TWinSparkle.OnError","href":"WinSparkle.TWinSparkle.OnError.htm"}
,{"title":"OnShutDown","key":"WinSparkle.TWinSparkle.OnShutDown","href":"WinSparkle.TWinSparkle.OnShutDown.htm"}
,{"title":"OnUpdateCancelled","key":"WinSparkle.TWinSparkle.OnUpdateCancelled","href":"WinSparkle.TWinSparkle.OnUpdateCancelled.htm"}
,{"title":"RegistryPath","key":"WinSparkle.TWinSparkle.RegistryPath","href":"WinSparkle.TWinSparkle.RegistryPath.htm"}
,{"title":"UpdateCheckInterval","key":"WinSparkle.TWinSparkle.UpdateCheckInterval","href":"WinSparkle.TWinSparkle.UpdateCheckInterval.htm"}
]}
,{"title":"Methods","key":"WinSparkle.TWinSparkle_Methods","href":"WinSparkle.TWinSparkle_Methods.htm","children":[{"title":"CheckUpdate(TUpdateType)","key":"WinSparkle.TWinSparkle.CheckUpdate(TUpdateType)","href":"WinSparkle.TWinSparkle.CheckUpdate.htm"}
,{"title":"CheckUpdateWithoutUI","key":"WinSparkle.TWinSparkle.CheckUpdateWithoutUI","href":"WinSparkle.TWinSparkle.CheckUpdateWithoutUI.htm"}
,{"title":"CheckUpdateWithUI","key":"WinSparkle.TWinSparkle.CheckUpdateWithUI","href":"WinSparkle.TWinSparkle.CheckUpdateWithUI.htm"}
,{"title":"CheckUpdateWithUIandInstall","key":"WinSparkle.TWinSparkle.CheckUpdateWithUIandInstall","href":"WinSparkle.TWinSparkle.CheckUpdateWithUIandInstall.htm"}
,{"title":"Cleanup","key":"WinSparkle.TWinSparkle.Cleanup","href":"WinSparkle.TWinSparkle.Cleanup.htm"}
,{"title":"Init","key":"WinSparkle.TWinSparkle.Init","href":"WinSparkle.TWinSparkle.Init.htm"}
,{"title":"ResetUpdateCheckInterval","key":"WinSparkle.TWinSparkle.ResetUpdateCheckInterval","href":"WinSparkle.TWinSparkle.ResetUpdateCheckInterval.htm"}
,{"title":"SetAppDetails(string,string,string)","key":"WinSparkle.TWinSparkle.SetAppDetails(string,string,string)","href":"WinSparkle.TWinSparkle.SetAppDetails.htm"}
,{"title":"SetLang(string)","key":"WinSparkle.TWinSparkle.SetLang(string)","href":"WinSparkle.TWinSparkle.SetLang.htm"}
,{"title":"SetLangID(ShortInt)","key":"WinSparkle.TWinSparkle.SetLangID(ShortInt)","href":"WinSparkle.TWinSparkle.SetLangID.htm"}
]}
]}
]}
,{"title":"Enumerations","key":"WinSparkle_Enumerations","href":"WinSparkle_Enumerations.htm","children":[{"title":"TCallbackType","key":"WinSparkle.TCallbackType","href":"WinSparkle.TCallbackType.htm"}
,{"title":"TCallbackTypeFunc","key":"WinSparkle.TCallbackTypeFunc","href":"WinSparkle.TCallbackTypeFunc.htm"}
,{"title":"TUpdateType","key":"WinSparkle.TUpdateType","href":"WinSparkle.TUpdateType.htm"}
]}
,{"title":"Types","key":"WinSparkle_Types","href":"WinSparkle_Types.htm","children":[{"title":"TCallbackArray","key":"WinSparkle.TCallbackArray","href":"WinSparkle.TCallbackArray.htm"}
,{"title":"TCallbackArrayFunctions","key":"WinSparkle.TCallbackArrayFunctions","href":"WinSparkle.TCallbackArrayFunctions.htm"}
]}
,{"title":"Variables","key":"WinSparkle_Variables","href":"WinSparkle_Variables.htm","children":[{"title":"callbackFuncs","key":"WinSparkle.callbackFuncs","href":"WinSparkle.callbackFuncs.htm"}
,{"title":"callbackProcs","key":"WinSparkle.callbackProcs","href":"WinSparkle.callbackProcs.htm"}
]}
,{"title":"Constants","key":"WinSparkle_Constants","href":"WinSparkle_Constants.htm","children":[{"title":"BugVersion","key":"WinSparkle.BugVersion","href":"WinSparkle.BugVersion.htm"}
,{"title":"MajorVersion","key":"WinSparkle.MajorVersion","href":"WinSparkle.MajorVersion.htm"}
,{"title":"MinorVersion","key":"WinSparkle.MinorVersion","href":"WinSparkle.MinorVersion.htm"}
,{"title":"WinSparkleLib","key":"WinSparkle.WinSparkleLib","href":"WinSparkle.WinSparkleLib.htm"}
]}
,{"title":"Routines","key":"WinSparkle_Routines","href":"WinSparkle_Routines.htm","children":[{"title":"DoOnCanShutdown","key":"WinSparkle.DoOnCanShutdown","href":"WinSparkle.DoOnCanShutdown.htm"}
,{"title":"DoOnError","key":"WinSparkle.DoOnError","href":"WinSparkle.DoOnError.htm"}
,{"title":"DoOnShutDown","key":"WinSparkle.DoOnShutDown","href":"WinSparkle.DoOnShutDown.htm"}
,{"title":"DoOnUpdateCancelled","key":"WinSparkle.DoOnUpdateCancelled","href":"WinSparkle.DoOnUpdateCancelled.htm"}
,{"title":"DoOnUpdateFound","key":"WinSparkle.DoOnUpdateFound","href":"WinSparkle.DoOnUpdateFound.htm"}
,{"title":"DoOnUpdateNotFound","key":"WinSparkle.DoOnUpdateNotFound","href":"WinSparkle.DoOnUpdateNotFound.htm"}
]}
]}
]}
]