[{"title":"neSparklePackage","key":"neSparklePackage","href":"neSparklePackage.htm","activate":true,"children":[{"title":"neSparkle","key":"neSparkle","href":"neSparkle.htm","children":[{"title":"Classes","key":"neSparkle_Classes","href":"neSparkle_Classes.htm","children":[{"title":"TneSparkle","key":"neSparkle.TneSparkle","href":"neSparkle.TneSparkle.htm","children":[{"title":"Constructors","key":"neSparkle.TneSparkle_Constructors","href":"neSparkle.TneSparkle_Constructors.htm","children":[{"title":"Create","key":"neSparkle.TneSparkle.Create","href":"neSparkle.TneSparkle.Create.htm"}
,{"title":"Create(string)","key":"neSparkle.TneSparkle.Create(string)","href":"neSparkle.TneSparkle.Create(string).htm"}
,{"title":"Destroy","key":"neSparkle.TneSparkle.Destroy","href":"neSparkle.TneSparkle.Destroy.htm"}
]}
,{"title":"Properties","key":"neSparkle.TneSparkle_Properties","href":"neSparkle.TneSparkle_Properties.htm","children":[{"title":"AppBuildVersion","key":"neSparkle.TneSparkle.AppBuildVersion","href":"neSparkle.TneSparkle.AppBuildVersion.htm"}
,{"title":"AppcastURL","key":"neSparkle.TneSparkle.AppcastURL","href":"neSparkle.TneSparkle.AppcastURL.htm"}
,{"title":"AutoCheckForUpdates","key":"neSparkle.TneSparkle.AutoCheckForUpdates","href":"neSparkle.TneSparkle.AutoCheckForUpdates.htm"}
,{"title":"DLLLoaded","key":"neSparkle.TneSparkle.DLLLoaded","href":"neSparkle.TneSparkle.DLLLoaded.htm"}
,{"title":"DLLPath","key":"neSparkle.TneSparkle.DLLPath","href":"neSparkle.TneSparkle.DLLPath.htm"}
,{"title":"DSAPublicPem","key":"neSparkle.TneSparkle.DSAPublicPem","href":"neSparkle.TneSparkle.DSAPublicPem.htm"}
,{"title":"LastCheckTime","key":"neSparkle.TneSparkle.LastCheckTime","href":"neSparkle.TneSparkle.LastCheckTime.htm"}
,{"title":"OnCanShutDown","key":"neSparkle.TneSparkle.OnCanShutDown","href":"neSparkle.TneSparkle.OnCanShutDown.htm"}
,{"title":"OnDidFindUpdate","key":"neSparkle.TneSparkle.OnDidFindUpdate","href":"neSparkle.TneSparkle.OnDidFindUpdate.htm"}
,{"title":"OnDidNotFindUpdate","key":"neSparkle.TneSparkle.OnDidNotFindUpdate","href":"neSparkle.TneSparkle.OnDidNotFindUpdate.htm"}
,{"title":"OnError","key":"neSparkle.TneSparkle.OnError","href":"neSparkle.TneSparkle.OnError.htm"}
,{"title":"OnShutDown","key":"neSparkle.TneSparkle.OnShutDown","href":"neSparkle.TneSparkle.OnShutDown.htm"}
,{"title":"OnUpdateCancelled","key":"neSparkle.TneSparkle.OnUpdateCancelled","href":"neSparkle.TneSparkle.OnUpdateCancelled.htm"}
,{"title":"RegistryPath","key":"neSparkle.TneSparkle.RegistryPath","href":"neSparkle.TneSparkle.RegistryPath.htm"}
,{"title":"UpdateCheckInterval","key":"neSparkle.TneSparkle.UpdateCheckInterval","href":"neSparkle.TneSparkle.UpdateCheckInterval.htm"}
]}
,{"title":"Methods","key":"neSparkle.TneSparkle_Methods","href":"neSparkle.TneSparkle_Methods.htm","children":[{"title":"CheckUpdate(TUpdateType)","key":"neSparkle.TneSparkle.CheckUpdate(TUpdateType)","href":"neSparkle.TneSparkle.CheckUpdate.htm"}
,{"title":"CheckUpdateWithoutUI","key":"neSparkle.TneSparkle.CheckUpdateWithoutUI","href":"neSparkle.TneSparkle.CheckUpdateWithoutUI.htm"}
,{"title":"CheckUpdateWithUI","key":"neSparkle.TneSparkle.CheckUpdateWithUI","href":"neSparkle.TneSparkle.CheckUpdateWithUI.htm"}
,{"title":"CheckUpdateWithUIandInstall","key":"neSparkle.TneSparkle.CheckUpdateWithUIandInstall","href":"neSparkle.TneSparkle.CheckUpdateWithUIandInstall.htm"}
,{"title":"Cleanup","key":"neSparkle.TneSparkle.Cleanup","href":"neSparkle.TneSparkle.Cleanup.htm"}
,{"title":"ExecuteReferencedFunctionBoolean(PWideChar,TCallbackTypeFunc,TFunc)","key":"neSparkle.TneSparkle.ExecuteReferencedFunctionBoolean(PWideChar,TCallbackTypeFunc,TFunc)","href":"neSparkle.TneSparkle.ExecuteReferencedFunctionBoolean.htm"}
,{"title":"ExecuteReferencedProcedure(PWideChar,TCallbackType,TProc)","key":"neSparkle.TneSparkle.ExecuteReferencedProcedure(PWideChar,TCallbackType,TProc)","href":"neSparkle.TneSparkle.ExecuteReferencedProcedure.htm"}
,{"title":"ExecuteSimpleProcedure(PWideChar)","key":"neSparkle.TneSparkle.ExecuteSimpleProcedure(PWideChar)","href":"neSparkle.TneSparkle.ExecuteSimpleProcedure.htm"}
,{"title":"GetAppBuildVersion","key":"neSparkle.TneSparkle.GetAppBuildVersion","href":"neSparkle.TneSparkle.GetAppBuildVersion.htm"}
,{"title":"GetAppcastURL","key":"neSparkle.TneSparkle.GetAppcastURL","href":"neSparkle.TneSparkle.GetAppcastURL.htm"}
,{"title":"GetAutoCheckForUpdates","key":"neSparkle.TneSparkle.GetAutoCheckForUpdates","href":"neSparkle.TneSparkle.GetAutoCheckForUpdates.htm"}
,{"title":"getDLLLoaded","key":"neSparkle.TneSparkle.getDLLLoaded","href":"neSparkle.TneSparkle.getDLLLoaded.htm"}
,{"title":"GetLastCheckTime","key":"neSparkle.TneSparkle.GetLastCheckTime","href":"neSparkle.TneSparkle.GetLastCheckTime.htm"}
,{"title":"GetRegistryPath","key":"neSparkle.TneSparkle.GetRegistryPath","href":"neSparkle.TneSparkle.GetRegistryPath.htm"}
,{"title":"GetUpdateCheckInterval","key":"neSparkle.TneSparkle.GetUpdateCheckInterval","href":"neSparkle.TneSparkle.GetUpdateCheckInterval.htm"}
,{"title":"Init","key":"neSparkle.TneSparkle.Init","href":"neSparkle.TneSparkle.Init.htm"}
,{"title":"ResetUpdateCheckInterval","key":"neSparkle.TneSparkle.ResetUpdateCheckInterval","href":"neSparkle.TneSparkle.ResetUpdateCheckInterval.htm"}
,{"title":"SetAppBuildVersion(string)","key":"neSparkle.TneSparkle.SetAppBuildVersion(string)","href":"neSparkle.TneSparkle.SetAppBuildVersion.htm"}
,{"title":"SetAppcastURL(string)","key":"neSparkle.TneSparkle.SetAppcastURL(string)","href":"neSparkle.TneSparkle.SetAppcastURL.htm"}
,{"title":"SetAppDetails(string,string,string)","key":"neSparkle.TneSparkle.SetAppDetails(string,string,string)","href":"neSparkle.TneSparkle.SetAppDetails.htm"}
,{"title":"SetAutoCheckForUpdates(Boolean)","key":"neSparkle.TneSparkle.SetAutoCheckForUpdates(Boolean)","href":"neSparkle.TneSparkle.SetAutoCheckForUpdates.htm"}
,{"title":"setDSAPublicPem(String)","key":"neSparkle.TneSparkle.setDSAPublicPem(String)","href":"neSparkle.TneSparkle.setDSAPublicPem.htm"}
,{"title":"SetLang(string)","key":"neSparkle.TneSparkle.SetLang(string)","href":"neSparkle.TneSparkle.SetLang.htm"}
,{"title":"SetLangID(ShortInt)","key":"neSparkle.TneSparkle.SetLangID(ShortInt)","href":"neSparkle.TneSparkle.SetLangID.htm"}
,{"title":"SetOnCanShutDown(TFunc)","key":"neSparkle.TneSparkle.SetOnCanShutDown(TFunc)","href":"neSparkle.TneSparkle.SetOnCanShutDown.htm"}
,{"title":"SetOnDidFindUpdate(TProc)","key":"neSparkle.TneSparkle.SetOnDidFindUpdate(TProc)","href":"neSparkle.TneSparkle.SetOnDidFindUpdate.htm"}
,{"title":"SetOnDidNotFindUpdate(TProc)","key":"neSparkle.TneSparkle.SetOnDidNotFindUpdate(TProc)","href":"neSparkle.TneSparkle.SetOnDidNotFindUpdate.htm"}
,{"title":"SetOnError(TProc)","key":"neSparkle.TneSparkle.SetOnError(TProc)","href":"neSparkle.TneSparkle.SetOnError.htm"}
,{"title":"SetOnShutDown(TProc)","key":"neSparkle.TneSparkle.SetOnShutDown(TProc)","href":"neSparkle.TneSparkle.SetOnShutDown.htm"}
,{"title":"SetOnUpdateCancelled(TProc)","key":"neSparkle.TneSparkle.SetOnUpdateCancelled(TProc)","href":"neSparkle.TneSparkle.SetOnUpdateCancelled.htm"}
,{"title":"SetRegistryPath(string)","key":"neSparkle.TneSparkle.SetRegistryPath(string)","href":"neSparkle.TneSparkle.SetRegistryPath.htm"}
,{"title":"SetUpdateCheckInterval(Integer)","key":"neSparkle.TneSparkle.SetUpdateCheckInterval(Integer)","href":"neSparkle.TneSparkle.SetUpdateCheckInterval.htm"}
]}
,{"title":"Fields","key":"neSparkle.TneSparkle_Fields","href":"neSparkle.TneSparkle_Fields.htm","children":[{"title":"fAppBuildVersion","key":"neSparkle.TneSparkle.fAppBuildVersion","href":"neSparkle.TneSparkle.fAppBuildVersion.htm"}
,{"title":"fAppcastURL","key":"neSparkle.TneSparkle.fAppcastURL","href":"neSparkle.TneSparkle.fAppcastURL.htm"}
,{"title":"fAppName","key":"neSparkle.TneSparkle.fAppName","href":"neSparkle.TneSparkle.fAppName.htm"}
,{"title":"fAppVersion","key":"neSparkle.TneSparkle.fAppVersion","href":"neSparkle.TneSparkle.fAppVersion.htm"}
,{"title":"fCompanyName","key":"neSparkle.TneSparkle.fCompanyName","href":"neSparkle.TneSparkle.fCompanyName.htm"}
,{"title":"fDLLPath","key":"neSparkle.TneSparkle.fDLLPath","href":"neSparkle.TneSparkle.fDLLPath.htm"}
,{"title":"fDSAPublicPem","key":"neSparkle.TneSparkle.fDSAPublicPem","href":"neSparkle.TneSparkle.fDSAPublicPem.htm"}
,{"title":"fHandle","key":"neSparkle.TneSparkle.fHandle","href":"neSparkle.TneSparkle.fHandle.htm"}
,{"title":"fOnCanShutDown","key":"neSparkle.TneSparkle.fOnCanShutDown","href":"neSparkle.TneSparkle.fOnCanShutDown.htm"}
,{"title":"fOnDidFindUpdate","key":"neSparkle.TneSparkle.fOnDidFindUpdate","href":"neSparkle.TneSparkle.fOnDidFindUpdate.htm"}
,{"title":"fOnDidNotFindUpdate","key":"neSparkle.TneSparkle.fOnDidNotFindUpdate","href":"neSparkle.TneSparkle.fOnDidNotFindUpdate.htm"}
,{"title":"fOnError","key":"neSparkle.TneSparkle.fOnError","href":"neSparkle.TneSparkle.fOnError.htm"}
,{"title":"fOnShutDown","key":"neSparkle.TneSparkle.fOnShutDown","href":"neSparkle.TneSparkle.fOnShutDown.htm"}
,{"title":"fOnUpdateCancelled","key":"neSparkle.TneSparkle.fOnUpdateCancelled","href":"neSparkle.TneSparkle.fOnUpdateCancelled.htm"}
,{"title":"fRegistryPath","key":"neSparkle.TneSparkle.fRegistryPath","href":"neSparkle.TneSparkle.fRegistryPath.htm"}
]}
]}
]}
,{"title":"Enumerations","key":"neSparkle_Enumerations","href":"neSparkle_Enumerations.htm","children":[{"title":"TCallbackType","key":"neSparkle.TCallbackType","href":"neSparkle.TCallbackType.htm"}
,{"title":"TCallbackTypeFunc","key":"neSparkle.TCallbackTypeFunc","href":"neSparkle.TCallbackTypeFunc.htm"}
,{"title":"TUpdateType","key":"neSparkle.TUpdateType","href":"neSparkle.TUpdateType.htm"}
]}
,{"title":"Types","key":"neSparkle_Types","href":"neSparkle_Types.htm","children":[{"title":"TCallbackArray","key":"neSparkle.TCallbackArray","href":"neSparkle.TCallbackArray.htm"}
,{"title":"TCallbackArrayFunctions","key":"neSparkle.TCallbackArrayFunctions","href":"neSparkle.TCallbackArrayFunctions.htm"}
]}
,{"title":"Constants","key":"neSparkle_Constants","href":"neSparkle_Constants.htm","children":[{"title":"BugVersion","key":"neSparkle.BugVersion","href":"neSparkle.BugVersion.htm"}
,{"title":"MajorVersion","key":"neSparkle.MajorVersion","href":"neSparkle.MajorVersion.htm"}
,{"title":"MinorVersion","key":"neSparkle.MinorVersion","href":"neSparkle.MinorVersion.htm"}
,{"title":"WinSparkleLib","key":"neSparkle.WinSparkleLib","href":"neSparkle.WinSparkleLib.htm"}
,{"title":"WinSparkleVersion","key":"neSparkle.WinSparkleVersion","href":"neSparkle.WinSparkleVersion.htm"}
]}
]}
]}
]