[{"title":"neSparklePackage","key":"neSparklePackage","href":"neSparklePackage.htm","activate":true,"children":[{"title":"neSparkle","key":"neSparkle","href":"neSparkle.htm","children":[{"title":"Classes","key":"neSparkle_Classes","href":"neSparkle_Classes.htm","children":[{"title":"TneSparkle","key":"neSparkle.TneSparkle","href":"neSparkle.TneSparkle.htm","children":[{"title":"Constructors","key":"neSparkle.TneSparkle_Constructors","href":"neSparkle.TneSparkle_Constructors.htm","children":[{"title":"Create","key":"neSparkle.TneSparkle.Create","href":"neSparkle.TneSparkle.Create.htm"}
,{"title":"Create(string)","key":"neSparkle.TneSparkle.Create(string)","href":"neSparkle.TneSparkle.Create(string).htm"}
,{"title":"Destroy","key":"neSparkle.TneSparkle.Destroy","href":"neSparkle.TneSparkle.Destroy.htm"}
]}
,{"title":"Properties","key":"neSparkle.TneSparkle_Properties","href":"neSparkle.TneSparkle_Properties.htm","children":[{"title":"AppBuildVersion","key":"neSparkle.TneSparkle.AppBuildVersion","href":"neSparkle.TneSparkle.AppBuildVersion.htm"}
,{"title":"AppcastURL","key":"neSparkle.TneSparkle.AppcastURL","href":"neSparkle.TneSparkle.AppcastURL.htm"}
,{"title":"AutoCheckForUpdates","key":"neSparkle.TneSparkle.AutoCheckForUpdates","href":"neSparkle.TneSparkle.AutoCheckForUpdates.htm"}
,{"title":"DLLLoaded","key":"neSparkle.TneSparkle.DLLLoaded","href":"neSparkle.TneSparkle.DLLLoaded.htm"}
,{"title":"DLLPath","key":"neSparkle.TneSparkle.DLLPath","href":"neSparkle.TneSparkle.DLLPath.htm"}
,{"title":"LastCheckTime","key":"neSparkle.TneSparkle.LastCheckTime","href":"neSparkle.TneSparkle.LastCheckTime.htm"}
,{"title":"OnCanShutDown","key":"neSparkle.TneSparkle.OnCanShutDown","href":"neSparkle.TneSparkle.OnCanShutDown.htm"}
,{"title":"OnDidFindUpdate","key":"neSparkle.TneSparkle.OnDidFindUpdate","href":"neSparkle.TneSparkle.OnDidFindUpdate.htm"}
,{"title":"OnDidNotFindUpdate","key":"neSparkle.TneSparkle.OnDidNotFindUpdate","href":"neSparkle.TneSparkle.OnDidNotFindUpdate.htm"}
,{"title":"OnError","key":"neSparkle.TneSparkle.OnError","href":"neSparkle.TneSparkle.OnError.htm"}
,{"title":"OnShutDown","key":"neSparkle.TneSparkle.OnShutDown","href":"neSparkle.TneSparkle.OnShutDown.htm"}
,{"title":"OnUpdateCancelled","key":"neSparkle.TneSparkle.OnUpdateCancelled","href":"neSparkle.TneSparkle.OnUpdateCancelled.htm"}
,{"title":"RegistryPath","key":"neSparkle.TneSparkle.RegistryPath","href":"neSparkle.TneSparkle.RegistryPath.htm"}
,{"title":"UpdateCheckInterval","key":"neSparkle.TneSparkle.UpdateCheckInterval","href":"neSparkle.TneSparkle.UpdateCheckInterval.htm"}
]}
,{"title":"Methods","key":"neSparkle.TneSparkle_Methods","href":"neSparkle.TneSparkle_Methods.htm","children":[{"title":"CheckUpdate(TUpdateType)","key":"neSparkle.TneSparkle.CheckUpdate(TUpdateType)","href":"neSparkle.TneSparkle.CheckUpdate.htm"}
,{"title":"CheckUpdateWithoutUI","key":"neSparkle.TneSparkle.CheckUpdateWithoutUI","href":"neSparkle.TneSparkle.CheckUpdateWithoutUI.htm"}
,{"title":"CheckUpdateWithUI","key":"neSparkle.TneSparkle.CheckUpdateWithUI","href":"neSparkle.TneSparkle.CheckUpdateWithUI.htm"}
,{"title":"CheckUpdateWithUIandInstall","key":"neSparkle.TneSparkle.CheckUpdateWithUIandInstall","href":"neSparkle.TneSparkle.CheckUpdateWithUIandInstall.htm"}
,{"title":"Cleanup","key":"neSparkle.TneSparkle.Cleanup","href":"neSparkle.TneSparkle.Cleanup.htm"}
,{"title":"Init","key":"neSparkle.TneSparkle.Init","href":"neSparkle.TneSparkle.Init.htm"}
,{"title":"ResetUpdateCheckInterval","key":"neSparkle.TneSparkle.ResetUpdateCheckInterval","href":"neSparkle.TneSparkle.ResetUpdateCheckInterval.htm"}
,{"title":"SetAppDetails(string,string,string)","key":"neSparkle.TneSparkle.SetAppDetails(string,string,string)","href":"neSparkle.TneSparkle.SetAppDetails.htm"}
,{"title":"SetLang(string)","key":"neSparkle.TneSparkle.SetLang(string)","href":"neSparkle.TneSparkle.SetLang.htm"}
,{"title":"SetLangID(ShortInt)","key":"neSparkle.TneSparkle.SetLangID(ShortInt)","href":"neSparkle.TneSparkle.SetLangID.htm"}
]}
]}
]}
,{"title":"Enumerations","key":"neSparkle_Enumerations","href":"neSparkle_Enumerations.htm","children":[{"title":"TCallbackType","key":"neSparkle.TCallbackType","href":"neSparkle.TCallbackType.htm"}
,{"title":"TCallbackTypeFunc","key":"neSparkle.TCallbackTypeFunc","href":"neSparkle.TCallbackTypeFunc.htm"}
,{"title":"TUpdateType","key":"neSparkle.TUpdateType","href":"neSparkle.TUpdateType.htm"}
]}
,{"title":"Types","key":"neSparkle_Types","href":"neSparkle_Types.htm","children":[{"title":"TCallbackArray","key":"neSparkle.TCallbackArray","href":"neSparkle.TCallbackArray.htm"}
,{"title":"TCallbackArrayFunctions","key":"neSparkle.TCallbackArrayFunctions","href":"neSparkle.TCallbackArrayFunctions.htm"}
]}
,{"title":"Variables","key":"neSparkle_Variables","href":"neSparkle_Variables.htm","children":[{"title":"callbackFuncs","key":"neSparkle.callbackFuncs","href":"neSparkle.callbackFuncs.htm"}
,{"title":"callbackProcs","key":"neSparkle.callbackProcs","href":"neSparkle.callbackProcs.htm"}
]}
,{"title":"Constants","key":"neSparkle_Constants","href":"neSparkle_Constants.htm","children":[{"title":"BugVersion","key":"neSparkle.BugVersion","href":"neSparkle.BugVersion.htm"}
,{"title":"MajorVersion","key":"neSparkle.MajorVersion","href":"neSparkle.MajorVersion.htm"}
,{"title":"MinorVersion","key":"neSparkle.MinorVersion","href":"neSparkle.MinorVersion.htm"}
,{"title":"WinSparkleLib","key":"neSparkle.WinSparkleLib","href":"neSparkle.WinSparkleLib.htm"}
,{"title":"WinSprkaleVersion","key":"neSparkle.WinSprkaleVersion","href":"neSparkle.WinSprkaleVersion.htm"}
]}
,{"title":"Routines","key":"neSparkle_Routines","href":"neSparkle_Routines.htm","children":[{"title":"DoOnCanShutdown","key":"neSparkle.DoOnCanShutdown","href":"neSparkle.DoOnCanShutdown.htm"}
,{"title":"DoOnError","key":"neSparkle.DoOnError","href":"neSparkle.DoOnError.htm"}
,{"title":"DoOnShutDown","key":"neSparkle.DoOnShutDown","href":"neSparkle.DoOnShutDown.htm"}
,{"title":"DoOnUpdateCancelled","key":"neSparkle.DoOnUpdateCancelled","href":"neSparkle.DoOnUpdateCancelled.htm"}
,{"title":"DoOnUpdateFound","key":"neSparkle.DoOnUpdateFound","href":"neSparkle.DoOnUpdateFound.htm"}
,{"title":"DoOnUpdateNotFound","key":"neSparkle.DoOnUpdateNotFound","href":"neSparkle.DoOnUpdateNotFound.htm"}
]}
]}
]}
]